#include <stdio.h>
#include <stdlib.h>

/*
  ANSI C program generated by devFlowcharter (https://github.com/albireo77/devflowcharter)
  for BubbleSort_C project
*/

#include <time.h> // se necesita esta libreria porque tiene funciones de tiempo que se necesitan en el programa.

#define ARRAY_SIZE 100 //definir un array con valor de 100 elementos.

int i; // se declara  i como variable tipo entero.
int change; // se declara variable CHANGE para registrar cambios en el orden del programa.
int n; //se declara n como variable tipo entero.
int a[ARRAY_SIZE]; // es un arreglo tipo entero para almacenar los elementos que se quieren ordenar.
int buf; // se declara buf como variable tipo entero que sirve para poner elementos mientras se ordena.
time_t seed; // es una variable para almacenar las semillas.

int main(int argc, char* argv[])
{
  seed = 0; // inicia el conteo de las semillas en 0.
  srand(time(&seed)); // se toma el tiempo.
  n = sizeof(a) / sizeof(*a); // calcular tamaño de arreglo a.

  for (i = 0; i <= n-1; i++) //se inicia un bucle con los numeros aleatorios de semillas.
  {
    a[i] = rand() % 1000; // adquiere nuevo valor.
  }

  for (i = 0; i <= n-1; i++) //se inicia un for para imprimir los elementos.
  {
    printf("Element a[%d]: %d\n", i, a[i]); // se imprime los elementos del arreglo con su índice.
  }

  change = 1; // para ordenar los números aleatorios.
  while (change == 1) //se inicia el orden con un bubble sort
  {
    change = 0; // no se necesita hacer el bucle cuando change vale 0
    for (i = 0; i <= n-2; i++) // el bucle es para realizar comparacion con las condiciones que se establece.
    {
      if (a[i] > a[i+1]) // Se esta preguntando si el primer termino es mayor que el segundo.
      {
        buf = a[i]; // se iguala.
        a[i] = a[i+1]; // se cambia el valor al valor que tiene la siguiente casilla.
        a[i+1] = buf; // buf ahora tiene el valor de a [i+1]
        change = 1; // necesita cambios, por lo que no se ha cerrado el bucle.
      }
    }
  }
  printf("\n----------------------------\n"); //para separar los numeros desordenados y ordenados.
  for (i = 0; i <= n-1; i++) // bucle para ordenar de menor a mayor
  {
    printf("Element a[%d]: %d\n", i, a[i]); //se imprime los elementos ordenados.
  }
  return 0; //fin del programa
}
